<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class products extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([
            [
                'product_name' => 'PET Cristal',
                'slug_product' => 'PC',
                'price_product_sale' => 2000,
                'price_product_purch_f' => 720,
                'price_product_purch_c' => 1800,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'PET Color',
                'slug_product' => 'PCO',
                'price_product_sale' => 700,
                'price_product_purch_f' => 200,
                'price_product_purch_c' => 500,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Plastico Revuelto',
                'slug_product' => 'PR',
                'price_product_sale' => 700,
                'price_product_purch_f' => 200,
                'price_product_purch_c' => 500,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Plastico Blanco',
                'slug_product' => 'PB',
                'price_product_sale' => 850,
                'price_product_purch_f' => 260,
                'price_product_purch_c' => 650,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Archivo Revuelto',
                'slug_product' => 'AR',
                'price_product_sale' => 850,
                'price_product_purch_f' => 260,
                'price_product_purch_c' => 650,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Archivo Blanco',
                'slug_product' => 'AB',
                'price_product_sale' => 1000, // Made up price.
                'price_product_purch_f' => 300, //Made up price
                'price_product_purch_c' => 850,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Soplado',
                'slug_product' => 'SO',
                'price_product_sale' => 1200, // Made up price.
                'price_product_purch_f' => 400, //Made up price
                'price_product_purch_c' => 900,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Vasija',
                'slug_product' => 'VA',
                'price_product_sale' => 800, // Made up price.
                'price_product_purch_f' => 250, //Made up price
                'price_product_purch_c' => 600,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Carton',
                'slug_product' => 'CA',
                'price_product_sale' => 650, // Made up price.
                'price_product_purch_f' => 150, //Made up price
                'price_product_purch_c' => 500,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Carton Plega',
                'slug_product' => 'CP',
                'price_product_sale' => 550, // Made up price.
                'price_product_purch_f' => 180, //Made up price
                'price_product_purch_c' => 400,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
             [
                'product_name' => 'Plegadiza',
                'slug_product' => 'PL',
                'price_product_sale' => 200, // Made up price.
                'price_product_purch_f' => 50, //Made up price
                'price_product_purch_c' => 100,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Vidrio',
                'slug_product' => 'VI',
                'price_product_sale' => 250, // Made up price.
                'price_product_purch_f' => 60, //Made up price
                'price_product_purch_c' => 120,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'AL Lata',
                'slug_product' => 'ALL',
                'price_product_sale' => 7500,
                'price_product_purch_f' => 2000,
                'price_product_purch_c' => 6100,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'AL Perfil',
                'slug_product' => 'ALP',
                'price_product_sale' => 8500,
                'price_product_purch_f' => 2500,
                'price_product_purch_c' => 7000,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Cobre # 1',
                'slug_product' => 'CO1',
                'price_product_sale' => 30000,
                'price_product_purch_f' => 10000,
                'price_product_purch_c' => 28000,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Cobre # 2',
                'slug_product' => 'CO2',
                'price_product_sale' => 26000,
                'price_product_purch_f' => 9000,
                'price_product_purch_c' => 24000,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Cable',
                'slug_product' => 'CAB',
                'price_product_sale' => 3500,
                'price_product_purch_f' => 1200,
                'price_product_purch_c' => 3000,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Cable Guaya',
                'slug_product' => 'CAG',
                'price_product_sale' => 9500,
                'price_product_purch_f' => 3000,
                'price_product_purch_c' => 8000,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Bronce',
                'slug_product' => 'BR',
                'price_product_sale' => 20000,
                'price_product_purch_f' => 6000,
                'price_product_purch_c' => 18000,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Al . Grueso',
                'slug_product' => 'ALG',
                'price_product_sale' => 6000,
                'price_product_purch_f' => 1800,
                'price_product_purch_c' => 5000,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Polietileno',
                'slug_product' => 'POL',
                'price_product_sale' => 650,
                'price_product_purch_f' => 150,
                'price_product_purch_c' => 500,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Acrilico',
                'slug_product' => 'ACR',
                'price_product_sale' => 1500,
                'price_product_purch_f' => 400,
                'price_product_purch_c' => 1200,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'PVC',
                'slug_product' => 'PVC',
                'price_product_sale' => 400,
                'price_product_purch_f' => 100,
                'price_product_purch_c' => 300,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Chatarra',
                'slug_product' => 'CHA',
                'price_product_sale' => 900,  // Made up price
                'price_product_purch_f' => 300,  // Made up price
                'price_product_purch_c' => 700,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Galon Aseo',
                'slug_product' => 'GA',
                'price_product_sale' => 1600, // Made up price
                'price_product_purch_f' => 500, // Made up price
                'price_product_purch_c' => 1300,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Galon Aceite',
                'slug_product' => 'GO',
                'price_product_sale' => 1800, // Made up price
                'price_product_purch_f' => 600, // Made up price
                'price_product_purch_c' => 1500,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Caneca',
                'slug_product' => 'CAN',
                'price_product_sale' => 1200,
                'price_product_purch_f' => 400,
                'price_product_purch_c' => 1000,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Canasta',
                'slug_product' => 'CAS',
                'price_product_sale' => 2400,
                'price_product_purch_f' => 800,
                'price_product_purch_c' => 2000,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Espuma',
                'slug_product' => 'ESP',
                'price_product_sale' => 650,
                'price_product_purch_f' => 200,
                'price_product_purch_c' => 500,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Acero',
                'slug_product' => 'ACE',
                'price_product_sale' => 3500,
                'price_product_purch_f' => 1200,
                'price_product_purch_c' => 3000,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Vasija Soplado',
                'slug_product' => 'VAS',
                'price_product_sale' => 900,
                'price_product_purch_f' => 300,
                'price_product_purch_c' => 700,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Revuelto',
                'slug_product' => 'REV',
                'price_product_sale' => 550, //Made up price
                'price_product_purch_f' => 150, //Made up
                'price_product_purch_c' => 400,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Periodico',
                'slug_product' => 'PER',
                'price_product_sale' => 1200, //Made up price
                'price_product_purch_f' => 400, //Made up
                'price_product_purch_c' => 1000,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Cercha',
                'slug_product' => 'CER',
                'price_product_sale' => 45000,
                'price_product_purch_f' => 15000,
                'price_product_purch_c' => 40000,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
             [
                'product_name' => 'Division Baño',
                'slug_product' => 'DIB',
                'price_product_sale' => 400, //Made up price
                'price_product_purch_f' => 100, //Made up
                'price_product_purch_c' => 300,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Tarjeta',
                'slug_product' => 'TAR',
                'price_product_sale' => 3000,
                'price_product_purch_f' => 1000,
                'price_product_purch_c' => 2500,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Olla',
                'slug_product' => 'OLA',
                'price_product_sale' => 6000,
                'price_product_purch_f' => 2000,
                'price_product_purch_c' => 5000,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Caneca Tapa',
                'slug_product' => 'CAT',
                'price_product_sale' => 4500,
                'price_product_purch_f' => 1500,
                'price_product_purch_c' => 4000,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Unicel',
                'slug_product' => 'UNIC',
                'price_product_sale' => 1800,
                'price_product_purch_f' => 600,
                'price_product_purch_c' => 1500,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Soplado Revuelto',
                'slug_product' => 'SOR',
                'price_product_sale' => 750, // Made up price
                'price_product_purch_f' => 250, // Made up price
                'price_product_purch_c' => 600,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Antimonio',
                'slug_product' => 'ANT',
                'price_product_sale' => 3000,
                'price_product_purch_f' => 1000,
                'price_product_purch_c' => 2500,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'CD',
                'slug_product' => 'CDU',
                'price_product_sale' => 650, // Made up price
                'price_product_purch_f' => 200, // Made up price
                'price_product_purch_c' => 500,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Tapa',
                'slug_product' => 'TAP',
                'price_product_sale' => 650, // Made up price
                'price_product_purch_f' => 200, // Made up price
                'price_product_purch_c' => 500,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Unidad',
                'slug_product' => 'UNI',
                'price_product_sale' => 3500,
                'price_product_purch_f' => 1200,
                'price_product_purch_c' => 3000,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Planchado',
                'slug_product' => 'PLA',
                'price_product_sale' => 1800,
                'price_product_purch_f' => 500,
                'price_product_purch_c' => 1500,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Blando',
                'slug_product' => 'BLA',
                'price_product_sale' => 400,
                'price_product_purch_f' => 100,
                'price_product_purch_c' => 300,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Enducido',
                'slug_product' => 'END',
                'price_product_sale' => 1200, // Made up price
                'price_product_purch_f' => 400, // Made up price
                'price_product_purch_c' => 1000,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Caratula',
                'slug_product' => 'CAR',
                'price_product_sale' => 900, // Made up price
                'price_product_purch_f' => 300, // Made up price
                'price_product_purch_c' => 700,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'AL Tarro',
                'slug_product' => 'ALT',
                'price_product_sale' => 6000,
                'price_product_purch_f' => 2000,
                'price_product_purch_c' => 5000,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Herramienta',
                'slug_product' => 'HER',
                'price_product_sale' => 12000,
                'price_product_purch_f' => 4000,
                'price_product_purch_c' => 10000,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'PET Aceite',
                'slug_product' => 'PETAC',
                'price_product_sale' => 650,
                'price_product_purch_f' => 200,
                'price_product_purch_c' => 500,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Tapas',
                'slug_product' => 'TPA',
                'price_product_sale' => 650,
                'price_product_purch_f' => 200,
                'price_product_purch_c' => 500,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Bateria',
                'slug_product' => 'BAT',
                'price_product_sale' => 3500,
                'price_product_purch_f' => 1200,
                'price_product_purch_c' => 3000,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
             [
                'product_name' => 'Galon Agua',
                'slug_product' => 'GAA',
                'price_product_sale' => 1600, // Made up price
                'price_product_purch_f' => 500,// Made up price
                'price_product_purch_c' => 1300,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Disket',
                'slug_product' => 'DIS',
                'price_product_sale' => 200, // Made up price
                'price_product_purch_f' => 50,  // Made up price
                'price_product_purch_c' => 100,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Desarme',
                'slug_product' => 'DES',
                'price_product_sale' => 1800,
                'price_product_purch_f' => 500,
                'price_product_purch_c' => 1500,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Archivo Plastico',
                'slug_product' => 'APL',
                'price_product_sale' => 400,
                'price_product_purch_f' => 100,
                'price_product_purch_c' => 300,
                'state' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
